import type {
  ShellContextualAction,
  ShellModuleRegistration,
  ShellRegistrationOverrides,
} from "@brightweblabs/app-shell";

/**
 * App-owned shell customizations. This scaffolded file is never overwritten by
 * `create-bw-app update`.
 *
 * @example Rewrite a module href wherever it appears in its registration:
 * ```ts
 * import { overrideNavHref } from "@brightweblabs/app-shell";
 *
 * const overrides: ShellRegistrationOverrides = {
 *   crm: (registration) => overrideNavHref(registration, "/admin/marketing", "/crm/marketing"),
 * };
 * ```
 */
export const shellRegistrationOverrides: ShellRegistrationOverrides = {};

/**
 * App-owned nav modules — surfaces this app implements itself, which no
 * BrightWeb package provides.
 *
 * `shellRegistrationOverrides` can only transform registrations that already
 * exist, so it cannot introduce a new one. Put app-owned surfaces here instead
 * of editing `config/shell.ts`, which is regenerated by `create-bw-app update`.
 *
 * @example An app-owned tool mounted under the Ferramentas section:
 * ```ts
 * import { BookOpen } from "lucide-react";
 *
 * export const additionalShellModules: ShellModuleRegistration<ShellContextualAction>[] = [
 *   {
 *     key: "tools",
 *     placement: "tools",
 *     navItems: [{ href: "/ferramentas/conteudos", label: "Conteúdos", icon: BookOpen, visibility: "admin" }],
 *     toolbarRoutes: [{ surface: "insights-cms", match: { prefixes: ["/ferramentas/conteudos"] } }],
 *   },
 * ];
 * ```
 */
export const additionalShellModules: ShellModuleRegistration<ShellContextualAction>[] = [];
