export const defaultProjectsUiDictionary = {
  locale: "pt-PT",
  portfolio: { title: "Projetos", emptyTitle: "Ainda não existem projetos", emptyHint: "Crie o primeiro projeto para começar.", loading: "A carregar projetos", updated: "Atualizado", refreshSuccess: "Projetos atualizados.", refreshError: "Não foi possível atualizar projetos.", invalidResponse: "Resposta inválida ao atualizar projetos.", total: "Total", planned: "A planear", active: "Ativos", atRisk: "Em risco", overdue: "Em atraso", page: (page: number, total: number) => `Página ${page} de ${total}`, projectCount: (count: number) => `${count} projeto${count === 1 ? "" : "s"}` },
  actions: { refresh: "Atualizar", create: "Novo", save: "Guardar", saving: "A guardar...", cancel: "Cancelar", edit: "Editar", delete: "Eliminar", retry: "Tentar novamente", close: "Fechar", add: "Adicionar", open: "Abrir", back: "Portfólio", tasks: "Tarefas" },
  detail: { overview: "Visão geral", recentActivity: "Atividade recente", recentActivitySubtitle: "Últimas alterações do projeto", fullActivity: "Atividade completa", fullActivityDescription: "Todas as alterações relacionadas com este projeto.", noActivity: "Sem atividade registada.", activityError: "Não foi possível carregar a atividade do projeto.", team: "Equipa", links: "Links", milestones: "Milestones", tasks: "Tarefas", cancellationReason: "Motivo do cancelamento", noCancellationReason: "Sem motivo registado.", noDate: "Sem data", noOwner: "Sem responsável", noSummary: "Sem resumo definido." },
  forms: { newProject: "Novo projeto", editProject: "Editar projeto", projectInformation: "Informação do projeto", name: "Nome", code: "Código", organization: "Organização", owner: "Responsável", status: "Estado", health: "Saúde", targetDate: "Data-alvo", summary: "Resumo", cancellationReason: "Motivo do cancelamento", newTask: "Nova tarefa", editTask: "Editar tarefa", newMilestone: "Nova milestone", editMilestone: "Editar milestone", newLink: "Novo link", editLink: "Editar link", title: "Título", description: "Descrição", priority: "Prioridade", assignee: "Responsável", dueDate: "Prazo", blockedReason: "Motivo de bloqueio", label: "Etiqueta", url: "URL", kind: "Tipo", visibility: "Visibilidade", members: "Membros", role: "Função", search: "Pesquisar..." },
  status: { planned: "A planear", active: "Ativo", blocked: "Bloqueado", completed: "Concluído", canceled: "Cancelado", on_track: "No rumo", at_risk: "Em risco", off_track: "Fora do rumo", todo: "Por fazer", in_progress: "Em progresso", done: "Concluída", pending: "Pendente", achieved: "Concluído", delayed: "Atrasado" },
  errors: { generic: "Ocorreu um erro.", createProject: "Não foi possível criar o projeto.", updateProject: "Não foi possível atualizar o projeto.", deleteProject: "Não foi possível eliminar o projeto.", loadActivity: "Falha ao carregar atividade do projeto.", createTask: "Não foi possível criar a tarefa.", createMilestone: "Não foi possível criar a milestone.", createLink: "Não foi possível criar o link.", updateMembers: "Não foi possível atualizar a equipa." },
} as const;
