export const projects = {
  generatedAt: "2026-07-24T12:00:00.000Z",
  kpis: {
    projectsActive: 1,
    projectsAtRisk: 0,
    projectsOverdue: 1,
    projectsDueNext7Days: 0,
    projectsWithoutOwner: 0,
    projectBlockedTasks: 1,
    projectsAttention: 1,
    projectsOnTrack: 0,
  },
  projects: {
    overdue: [{
      id: "project-1",
      organizationName: "BrightWeb",
      name: "Platform",
      code: null,
      status: "active",
      health: "at_risk",
      ownerLabel: null,
      targetDate: "2026-07-25",
      taskStats: { total: 2, done: 1, overdue: 1, blocked: 1 },
    }],
    attention: [{
      id: "project-1",
      organizationName: "BrightWeb",
      name: "Platform",
      code: null,
      status: "active",
      health: "at_risk",
      ownerLabel: null,
      targetDate: "2026-07-25",
      taskStats: { total: 2, done: 1, overdue: 1, blocked: 1 },
      attentionReason: "overdue",
    }],
    milestones: [{
      id: "milestone-1",
      projectId: "project-1",
      projectName: "Platform",
      projectCode: null,
      title: "Dashboard shipped",
      status: "in_progress",
      targetDate: "2026-07-25",
    }],
    milestonesNext7Days: [{
      id: "milestone-week-1",
      projectId: "project-1",
      projectName: "Platform",
      projectCode: null,
      title: "Weekly dashboard shipped",
      status: "pending",
      targetDate: "2026-07-26",
    }],
  },
};

export const crm = {
  generatedAt: "2026-07-24T12:00:00.000Z",
  kpis: {
    crmTotalContacts: 2,
    crmNewLast7Days: 1,
    crmNewLast30Days: 1,
    crmNewLastYear: 2,
    crmUnassignedContacts: 0,
  },
  crm: {
    statusBreakdown: { lead: 1, qualified: 1, proposal: 0, won: 0, lost: 0 },
    recentChanges: [{
      id: "change-1",
      contactId: "contact-1",
      contactLabel: "Ada",
      previousStatus: null,
      newStatus: "lead",
      changedAt: "2026-07-24T12:00:00.000Z",
    }],
    recentContacts: [{
      id: "contact-1",
      name: "Ada",
      company: null,
      status: "lead",
      lastChangedAt: "2026-07-24T12:00:00.000Z",
    }],
  },
};

export const tasks = {
  generatedAt: "2026-07-24T12:00:00.000Z",
  kpis: { total: 1, dueThisWeek: 1, overdue: 0, blocked: 0 },
  tasks: [{
    id: "task-1",
    projectId: "project-1",
    projectName: "Platform",
    projectCode: null,
    title: "Harden dashboard",
    status: "in_progress",
    priority: "high",
    dueDate: null,
    blockedReason: null,
    milestoneId: null,
    updatedAt: "2026-07-24T12:00:00.000Z",
  }],
  attention: {
    total: 1,
    tasks: [{
      id: "task-1",
      projectId: "project-1",
      projectName: "Platform",
      projectCode: null,
      title: "Harden dashboard",
      status: "in_progress",
      priority: "high",
      dueDate: null,
      blockedReason: null,
      milestoneId: null,
      updatedAt: "2026-07-24T12:00:00.000Z",
    }],
  },
  pagination: { page: 1, pageSize: 50, hasMore: false },
};
